spring:

  profiles:
    active: @activatedProperties@

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          # CommonOAuth2Provider
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            provider: github
            client-name: Github
            scope:
              - identify
              - user:email

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            provider: google
            client-name: Google
            scope:
              - profile
              - email

          # CustomOAuth2Provider
          discord:
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Discord
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope:
              - identify
              - email
        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username

logging:
  level:
    org.springframework.security: debug