spring:

  profiles:
    active: @activatedProperties@

  security:
    oauth2:
      client:
        registration:
          # CommonOAuth2Provider
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: github
            client-name: Github
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope:
              - identify
              - user:email

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: google
            client-name: Google
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope:
              - profile
              - email

          # CustomOAuth2Provider
          discord:
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Discord
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope:
              - identify
              - email
        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username

logging:
  level:
    org.springframework.security: debug